import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next.js, hunting coder blog, hunting coder" />
        <link rel="icon" href="/favcon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.imagerap}>
          <img className={styles.homeImg} src="/home.jpg" alt="hunting coder"></img>
        </div>
        <h1 className={styles.title}>
          Hunting Coder
        </h1>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        <div className={styles.blogs}>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className={styles.blogitem}>
            <h3 className={styles.h3}>How to learn javaScript in 2022?</h3>
            <p className={styles.p}>Its time to learn practical JavaScript the  modern way</p>
            <button className={styles.btnprimary}>Read More</button>
          </div>
          <div className={styles.blogitem}>
            <h3 className={styles.h3}>How to learn javaScript in 2022?</h3>
            <p className={styles.p}>Its time to learn practical JavaScript the  modern way</p>
            <button className={styles.btnprimary}>Read More</button>
          </div>
          <div className={styles.blogitem}>
            <h3 className={styles.h3}>How to learn javaScript in 2022?</h3>
            <p className={styles.p}>Its time to learn practical JavaScript the  modern way</p>
            <button className={styles.btnprimary}>Read More</button>
          </div>
        </div>
      </main >
    </div >
  )
}
